{% set name = "ptmcmcsampler" %}
{% set version = "2.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ptmcmcsampler-{{ version }}.tar.gz
  sha256: 2e44a3b3cc7056a532c3a045e7e6e77cd57c7a2f7cdb41fbbf249882ac9825dd

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools >=45
    - setuptools-scm >=6.2
  run:
    - numpy >=1.16.3
    - python >=3.6
    - scipy >=1.2.0

test:
  imports:
    - PTMCMCSampler
  commands:
    - pip check
  requires:
    - pip

# NOTE: licence file can be removed from recipe in next release
# as it will be packaged in source dist
about:
  home: https://github.com/jellis18/PTMCMCSampler
  summary: Parallel tempering MCMC sampler written in Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AaronDJohnson
    - vhaasteren
    - paulthebaker
    - jellis18
