{% set name = "ptmcmcsampler" %}
{% set version = "2.1.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ptmcmcsampler-{{ version }}.tar.gz
  sha256: 954892f4d1e24fb0b412cc437dd0b210faaa1500e147ae99b2217956de8a2943

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - setuptools
    - wheel
    - python >=3.8
  run:
    - numpy >=1.16.3
    - python >=3.8
    - scipy >=1.2.0

test:
  imports:
    - PTMCMCSampler
  commands:
    - pip check
  requires:
    - pip

# NOTE: licence file can be removed from recipe in next release
# as it will be packaged in source dist
about:
  home: https://github.com/nanograv/PTMCMCSampler
  summary: Parallel tempering MCMC sampler written in Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AaronDJohnson
    - vhaasteren
    - paulthebaker
    - jellis18
